@startuml
!include style.puml

skinparam arrowFontSize 15
skinparam participantFontSize  15

mainframe **sd**    delete contacts
box  Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "d_result:CommandResult" as CommandResult2 LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

activate LogicManager
LogicManager-> AddressBookParser: parseCommand(\n"/contactsTab \ndelete 1")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser-> DeleteCommandParser
activate DeleteCommandParser
DeleteCommandParser --> AddressBookParser
deactivate

AddressBookParser-> DeleteCommandParser : parse("1")
activate DeleteCommandParser


create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

AddressBookParser <-- DeleteCommandParser : d
deactivate DeleteCommandParser
destroy DeleteCommandParser

LogicManager<-- AddressBookParser: d
deactivate AddressBookParser


ref over LogicManager, AddressBookParser
    go to contacts tab
end ref

LogicManager -> DeleteCommand : d.execute()
activate DeleteCommand

DeleteCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult2
DeleteCommand -> CommandResult2
activate CommandResult2

CommandResult2 --> DeleteCommand : d_result
deactivate CommandResult2

DeleteCommand --> LogicManager : d_result
deactivate DeleteCommand

@enduml
