@startuml
!include style.puml

skinparam arrowFontSize 15
skinparam participantFontSize  15

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("\n/contactsTab \ndelete 1")
activate LogicManager

activate AddressBookParser

ref over LogicManager, AddressBookParser, Model
    delete contacts
end ref

[<--LogicManager
deactivate LogicManager
@enduml
