@startuml

!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class JsonAdaptedPolicy
Class JsonAdaptedTodo
Class JsonAdaptedSchedule
Class JsonAdaptedCustomGoal
}

package "Schedule Storage" #F4F6F6{
Interface ScheduleStorage <<Interface>>
Class IcsScheduleStorage
Class IcsAdaptedSchedule
}

}
Class HiddenOutside_2 #FFFFFF
HiddenOutside_2 ..> ScheduleStorage

Class HiddenOutside_1 #FFFFFF
HiddenOutside_1 ..> Storage


StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonSerializableAddressBook --> "*" JsonAdaptedTodo
JsonSerializableAddressBook --> "*" JsonAdaptedSchedule
JsonSerializableAddressBook --> "*" JsonAdaptedCustomGoal
JsonAdaptedTodo --> "*" JsonAdaptedTag
JsonAdaptedSchedule --> "*" JsonAdaptedTag
JsonAdaptedCustomGoal --> "*" JsonAdaptedTag
JsonAdaptedPerson --> "*" JsonAdaptedPolicy

IcsScheduleStorage .up.|> ScheduleStorage
IcsScheduleStorage ..> IcsAdaptedSchedule



@enduml
