@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class AnalyticsPanel
Class PersonDetailedPanel
Class PolicyListPanel
Class PolicyListCard
Class NotesPanel
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
Class HelpWindow
Class ImportWindow
Class XYZListPanel
Class XYZCard
Class PersonCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-->  "1" CommandBox
MainWindow *-down--> "1" ResultDisplay
MainWindow *-down--> "1" StatusBarFooter
MainWindow *-down--> "1" AnalyticsPanel
MainWindow *-down--> "1" PersonDetailedPanel
MainWindow *-down--> "1" PolicyListPanel
MainWindow *-down--> "1" NotesPanel
MainWindow *-down--> "1" XYZListPanel
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" ImportWindow

PolicyListPanel -down-> "*" PolicyListCard
XYZListPanel -down-> "*" XYZCard
PersonDetailedPanel -down-> "*" PersonCard

MainWindow -left-|> UiPart

PersonCard --|> UiPart
PersonDetailedPanel --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
AnalyticsPanel --|> UiPart
PolicyListPanel --|> UiPart
PolicyListCard--|> UiPart
NotesPanel --|> UiPart
ImportWindow--|> UiPart
XYZListPanel--|> UiPart
XYZCard--|> UiPart

PersonCard ...> Model
AnalyticsPanel ...> Model
PolicyListCard ...> Model
XYZCard ...> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PolicyListPanel -[hidden]down- PolicyListCard
XYZListPanel -[hidden]left- PolicyListPanel
XYZListPanel -[hidden]left- NotesPanel
XYZListPanel -[hidden]left- PersonDetailedPanel
XYZListPanel -[hidden]left- AnalyticsPanel
XYZListPanel -[hidden]left- NotesPanel

HelpWindow -[hidden]down- XYZListPanel
StatusBarFooter -[hidden]down- XYZListPanel
ResultDisplay -[hidden]down- XYZListPanel
CommandBox-[hidden]down- XYZListPanel
ImportWindow -[hidden]down- XYZListPanel
HelpWindow -[hidden]down- NotesPanel


'HelpWindow -[hidden]left- CommandBox
'CommandBox -[hidden]left- ResultDisplay
'ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
