@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class AnalyticsPanel
Class CustomGoalListPanel
Class CustomGoalCard
Class PersonListPanel
Class PersonCard
Class PersonDetailedPanel
Class PolicyListPanel
Class PolicyListCard
Class NotesPanel
Class TodoListPanel
Class TodoCard
Class ScheduleListPanel
Class ScheduleCard
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
Class HelpWindow
Class ImportWindow
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" AnalyticsPanel
MainWindow *-down-> "1" CustomGoalListPanel
MainWindow *-down-> "1" PersonDetailedPanel
MainWindow *-down-> "1" PolicyListPanel
MainWindow *-down-> "1" NotesPanel
MainWindow *-down-> "1" TodoListPanel
MainWindow *-down-> "1" ScheduleListPanel
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" ImportWindow

PersonListPanel -down-> "*" PersonCard
CustomGoalListPanel -down-> "*" CustomGoalCard
PersonDetailedPanel -down-> "*" PersonCard
PolicyListPanel -down-> "*" PolicyListCard
TodoListPanel -down-> "*" TodoCard
ScheduleListPanel -down-> "*" ScheduleCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
AnalyticsPanel --|> UiPart
CustomGoalCard --|> UiPart
CustomGoalListPanel--|> UiPart
PolicyListPanel --|> UiPart
PolicyListCard--|> UiPart
NotesPanel --|> UiPart
TodoListPanel --|> UiPart
TodoCard --|> UiPart
ScheduleListPanel --|> UiPart
ScheduleCard --|> UiPart
ImportWindow--|> UiPart

PersonCard ...> Model
AnalyticsPanel ...> Model
ScheduleCard ...> Model
TodoCard ...> Model
PolicyListCard ...> Model
CustomGoalCard ...> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- AnalyticsPanel
PersonListPanel -[hidden]left- PersonDetailedPanel
PersonListPanel -[hidden]left- NotesPanel
PersonListPanel -[hidden]left- ScheduleListPanel
PersonListPanel -[hidden]left- CustomGoalListPanel
PersonListPanel -[hidden]left- TodoListPanel

PersonListPanel -[hidden]down- PersonCard
PolicyListPanel -[hidden]down- PolicyListCard
ScheduleListPanel -[hidden]down- ScheduleCard
CustomGoalListPanel -[hidden]down- CustomGoalCard

HelpWindow -[hidden]down- TodoListPanel

'CustomGoalCard -[hidden]down- ImportWindow
'HelpWindow -[hidden]left- CommandBox
'CommandBox -[hidden]left- ResultDisplay
'ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
